name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js v20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Install AWS CDK
        run: npm install -g aws-cdk@2.131.0
      - name: Build app
        working-directory: app
        run: mvn -B package
      - name: Build infrastructure
        working-directory: infrastructure
        run: mvn -B package
      - name: Synthesize infrastructure
        working-directory: infrastructure
        env:
          STACK_PREFIX: "demo"
        run: cdk synth
      - name: Run app locally
        working-directory: app
        run: mvn exec:java "-Dexec.args=example-event.json"
